language: node_js

node_js:
  - "0.12"
  - "0.10"
  - "iojs"

before_install:
  - npm install -g gulp bower
  - bower install

env:
  global:
    - secure: f2UbDM8GQ3OG101fiTnVu2RqwQuIBbbxmCowh9aQhTlA2SxIzoMTPX0i0uR4aMee3rAdOF8rWBg5+AdR3YJQpuEqAOd2acsqT0wCMb+GupaVCOU9N7r7Do5k6KzrqzaLG8UHD7FY9BWyT+jC8gS5pqsztt6w38DHzTO2sSsMQQbQwGq+SDiRXSFNspYmnMnQPha84CoFzPX0oGmLQ3QhArI0572PpcJ4vZYUEzPyGU/qA7aofkyebFRY4TLjtltzNYq3d3Fp/1t7qd6QqGrZnXyRUd+9YMq1/qRD+7YKitGe+YM1ffknMlRZsKyIv3Da3Xdh2jomQ3JK6j39rY8l3aFsiUFQMdE2AuOlfthUkw+GxRcjFunapvwBtRqUA1hdI9lZI7ERR9/8ndzURXSjGG6kKXwWSL/anTijbdtQyndqLQZ++BlDiZKpQ06fi4MSfjtfymrvPFQJ1ehCxZHoDBycaO730LwUgq7+Beq8iCfJlTlgGvN6ghj2Y+zOmoUw56cWqRP5/NI4UtKBmqwxVKWjvR5dat3uWI2dqMVLHOSFd6xCtSm0tZ8QqbY0P89JskvFTP8OYUNrDq2gefX+Rqst0NFdIyEpIfzcoflIyZ3c7mokw6iVJWEZTEeDL873IBn5adnPOL5LpTkuiB5rgq8s6RxgGmvGopTzK9kNnuw=
    - secure: QMIPkKoer3+Oo4Is1m39+jW1jAO7oKYCwdi1c4c/j0uFQN4cJ9I88q4nf1xqKoFqJaXxdwIb4KVNUTD9A8J9G5R0bIPnhf0yfN9fR8k3uQAzwG8De2Wlns709AmqoYoJvODvt9qqDO/ui0lzJgqlOlng0hdPxYA12xXZkURKedw5G8W/nQliSBt5F3o3+hqARsgGnCzTxdjI2RlxNXpOlSFPMYKoSgmocQrcyufkDZGM0j+hBHRzhGj/aFnCAvZWqW3TcuVcfJZ8Ge7W23pJgkhlKHoVbXdc6l8mQXzQ3mg+lRZOH0XeDuVviaZjMWPD4QKmOepp8hG7LGo658zwyxyIatggTlCxVlBPF8p2cqSXQbtpUi3RUw4UWfD71EhT4CrOEUrMoJF9i5Y8R0olXT9/jp51OhUw6v657Bxv8G4X4N2GYgci32waTzqwAPg1fdeKBkvYdFhJUy2/GZIRA+OPSx2C0nDpo/Itn9mAV9KbQ+omoxkWZvN8GvLxwcLXf/V+4eLK2Q+wqHTy1pt8wQ+D19KYSxsp2JK5TA1Ray1N9ihkIlRSUsANAG6s2fLXlzxP/JxnW4lzL3O3rwFCTHI2RobTW6yDw4mXAw+rQ0SYBXSXgGrhIhz5VI80tJUBFUF9x0ghmzMb0Pg1S/gPbxcFLSSjiZsz9OgnQf2xQ0U=
